#!/bin/sh
if [ -z "$1" ]
  then
    echo "Usage: apk2gold apk_file"
    echo
    echo "Arguments:"
    echo "apk_file        the APK package to be reverse engineered"
    exit 1
fi
MPATH=`dirname $0`
FOLDER=`echo $1 | sed -e 's/\.apk//g'`
$MPATH/apktool/apktool d -f $1
mkdir $FOLDER/src
mv $FOLDER/smali $FOLDER/.smali
$MPATH/dex2jar-0.0.9.15/d2j-dex2jar.sh $1
echo "Converting .class files to java..."
java -jar $MPATH/jd-cli.jar ${FOLDER}-dex2jar.jar -od $FOLDER/src
mv ${FOLDER}-dex2jar.jar $FOLDER/classes.jar
unzip $FOLDER/classes.jar -d $FOLDER/classes
python $MPATH/rreassoc.py ${FOLDER}
